### ISSUE TITLE
New Traefik/Consul doesn't work well with Portainer

### ISSUE THREAD

**Issue by lukebrewerton** [BretFisher/dogvscat#15]
Hi Bret,

Great work on this repo, I have been following it for some time! I was trying out the new Traefik HA and I have found that the Portainer stack does some weird things through this new Traefik stack. 

1. When creating the Admin user it shows that it could not create the user but it in fact has
2. when adding an endpoint, selecting that endpoint to view the settings brings up blank settings
3. Unable to view any containers, services etc
4. A lot of 404 errors being returned in the browser console so it looks like some traffic is getting lost along the way.

This is not reproducible when using the single instance traefik. I have also tested older traefik and portainer versions but I still get the same results.

**Comment by BretFisher** [comment]
I’m not sure how portainer is changed by the new proxy setup. Did you
change anything with it? Portainer should be using it’s agents to talk to
each server.

**Comment by lukebrewerton** [comment]
It seems that the Digital Ocean Load Balancers don't work well with the new setup. Passing traffic direct to the nodes gets around this issue so it seems the load balancer is not passing the traffic correctly.
