### ISSUE TITLE
PR: create labels

### ISSUE THREAD

**Issue by pascalandy** [BretFisher/dogvscat#18]
If it makes sense with you, I'll do a PR.
 
## prerequisite

```
# machine name prefix
export node_prefix="alga"
```

## label my nodes

```
#!/bin/bash
# set -x

# add label on managers
for server_id in {1..3}; do

  this_node=$(docker-machine ls | awk '{print $1}' | grep ${server_id} | tail -n1)

  docker-machine ssh ${node_prefix}${server_id} docker node update --label-add nodeid=${server_id} ${this_node}
  docker-machine ssh ${node_prefix}${server_id} docker node update --label-add nodename=${this_node} ${this_node}
  docker-machine ssh ${node_prefix}${server_id} docker node update --label-add nodetype="manager" ${this_node}
  docker-machine ssh ${node_prefix}${server_id} docker node update --label-add nodetag=${node_prefix} ${this_node}

done

# add label on workers (in the future I'll have more)
#.
#.
#.
#.
```

**Comment by BretFisher** [comment]
Hey thanks for the idea, but not sure why we need this in my example of deploying a few apps and ops tools. I'm also not sure why you would use some of those labels like nodename and nodetype.

**Comment by pascalandy** [comment]
I know it might be overkill for basic a use case. On my side, I need nodeid to force the deployment of Resilio on a specific node. Resilio sync data between nodes (no matter if they are in swarm or not). 

I agree that nodetype is a duplicate from a label already supported by Docker. I was more for me to brainstorm about the possibilities. 

Feel free to close.
