### ISSUE TITLE
PR: create node in parallel (instead of one after the other)

### ISSUE THREAD

**Issue by pascalandy** [BretFisher/dogvscat#21]
As we can execute bash commands to run in parallel, I manage to create y nodes in parallel :) 
Much faster.

**Comment by BretFisher** [comment]
The current shell script is async AFAIK.

**Comment by pascalandy** [comment]
Humm, from what I could observe, docker-machine script creates the node-n1, then once done, it starts the second one and so on.

**Comment by BretFisher** [comment]
The `&` at the end of each command in the bash loop frees the loop to start the next loop before the previous command finishes. See creation here and how the responses are async:

[![asciicast](https://asciinema.org/a/VCFBMalDNttmC7VlriBCjTE9D.svg)](https://asciinema.org/a/VCFBMalDNttmC7VlriBCjTE9D)

**Comment by pascalandy** [comment]
Oh! In the script version I have, (dec 2018), the `&` was not there! That's why I was confused.
Good to know!

> The & at the end of each command
