### ISSUE TITLE
RexRay doesn't work on Docker latest (19)

### ISSUE THREAD

**Issue by syntaqx** [BretFisher/dogvscat#24]
https://github.com/BretFisher/dogvscat/blob/master/stack-rexray.yml

Using `docker stack deploy -c stack-rexray.yml rexray` gives back the following error:

```
network "bridge" is declared as external, but it is not in the right scope: "local" instead of "swarm"
```

Would love to see what those TODO notes resolve into as well as this has been very useful for my swarm.

**Comment by BretFisher** [comment]
Did that work for you?
