### ISSUE TITLE
Step to create rexray secrets

### ISSUE THREAD

**Issue by kaustavb12** [BretFisher/dogvscat#30]
Hi @BretFisher 

Following the steps of deployment in [README](https://github.com/BretFisher/dogvscat/blob/master/README.md),
in Step 1, the `REXRAY_DO_TOKEN` env. variable is set and in Step 5, external secrets `rexray_do_token` is used during deployment of the rexray stack.

However this secret is not created at any step prior to Step 5.

A command such as  `echo $REXRAY_DO_TOKEN | docker secret create rexray_do_token -` could be included in Step 5, prior to the stack deployment command or a new step 5 can be added can be added and subsequent steps renumbered.

I could open a PR for the same, if you agree.

**Comment by BretFisher** [comment]
Sure, just add it to step one in a PR, thanks.
